### ISSUE TITLE
Broken fitting of fit results

### ISSUE THREAD

**Issue by dfujim** [dfujim/bfit#120]
**Describe the bug**
When trying to fit the results on the fit tab. Function parameter recognition not working

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.10/tkinter/__init__.py", line 1921, in __call__
    return self.func(*args)
  File "/home/bnmr/py310venv/lib/python3.10/site-packages/bfit/gui/template_fit_popup.py", line 201, in get_input
    self.do_after_parse(*out)
  File "/home/bnmr/py310venv/lib/python3.10/site-packages/bfit/gui/popup_fit_results.py", line 322, in do_after_parse
    self.new_par = self.new_par.append({'name':k, **self.default_parvals},
  File "/home/bnmr/py310venv/lib/python3.10/site-packages/pandas/core/generic.py", line 6299, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'append'
```

**Comment by dfujim** [comment]
Fixed in aafb46d8eecaa58b32e402912b4f59a163e6d30d and 329e064589f4faed67971ccb461ddb6b55afccbf
