### ISSUE TITLE
Issue with fetch last run in file details

### ISSUE THREAD

**Issue by dfujim** [dfujim/bfit#51]
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/bnmr/.local/lib/python3.7/site-packages/bfit/gui/tab_fileviewer.py", line 256, in get_data
    self.bfit.set_asym_calc_mode_box(data.mode,self)
  File "/home/bnmr/.local/lib/python3.7/site-packages/bfit/gui/bfit.py", line 1418, in set_asym_calc_mode_box
    modes = self.asym_dict_keys[mode]
KeyError: ''
```

**Comment by dfujim** [comment]
Issue with run mode not being written.
