### ISSUE TITLE
problem on openSuSE 15.1

### ISSUE THREAD

**Issue by gdm2197** [dfujim/bfit#53]
Error on drawing:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/home/gmorris/.local/lib/python3.6/site-packages/bfit/gui/tab_fetch_files.py", line 754, in <lambda>
    command=lambda:self.draw(figstyle='data'),
  File "/home/gmorris/.local/lib/python3.6/site-packages/bfit/gui/tab_fetch_files.py", line 888, in draw
    label=self.label.get())
  File "/home/gmorris/.local/lib/python3.6/site-packages/bfit/gui/bfit.py", line 995, in draw
    raise_window()
  File "/home/gmorris/.local/lib/python3.6/site-packages/bfit/backend/raise_window.py", line 10, in raise_window
    wm.canvas.get_tk_widget().focus_force()
AttributeError: 'FigureCanvasGTK3Agg' object has no attribute 'get_tk_widget'
```

**Comment by dfujim** [comment]
Resolved in 2ed0bf9a8b5fc6a23a62159b5a0e14515f13fdda
