### ISSUE TITLE
no graph generated

### ISSUE THREAD

**Issue by gdm2197** [dfujim/bfit#94]
Hi Derek,
Just updated bfit, and it broke. A graph window opens but no plot is generated.

Error message generated :
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib64/python3.6/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/gmorris/.local/lib/python3.6/site-packages/bfit/gui/tab_fileviewer.py", line 76, in <lambda>
    command=lambda:self.draw(figstyle='inspect'))
  File "/home/gmorris/.local/lib/python3.6/site-packages/bfit/gui/tab_fileviewer.py", line 200, in draw
    figstyle=figstyle)
  File "/home/gmorris/.local/lib/python3.6/site-packages/bfit/gui/bfit.py", line 883, in draw
    nbm=self.use_nbm.get())
  File "/home/gmorris/.local/lib/python3.6/site-packages/bfit/backend/fitdata.py", line 103, in asym
    return self.bd.asym(*args, deadtime=deadtime, **kwargs)
TypeError: asym() got an unexpected keyword argument 'deadtime'

**To Reproduce**
Fetch a run.
Draw any spectrum.

**Expected behavior**
Plot expected.

**Desktop (please complete the following information):**
 - OS: OpenSUSE Leap 15.2
 - Python 3.6.12

**Additional context**
Deadtime correction controls make no difference.
Draw mode, existing or new window make no difference.

**Comment by dfujim** [comment]
Ah yes. This was an update to bdata, and apparently I broke the dependency requirements for bfit. Should be fixed now.

**Comment by gdm2197** [comment]
Quick test finds it's working again.
